apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: long-name-which-goes-on-and-on-and-on-until-it-exceeds-63-characters
  namespace: flux-system
spec:
  interval: 1m
  path: "./label-length/kustomization-long"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-bug-test
  timeout: 5m
