apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: short-name
  namespace: flux-system
spec:
  interval: 1m
  path: "./label-length/kustomization-short"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-bug-test
  timeout: 5m
